# Generated by Django 3.0.5 on 2020-10-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CURD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curd',
            name='image_url',
            field=models.URLField(default=None),
        ),
    ]
